version: '3'
services:
  coupons:
    build:
      context: .
    restart: always
    environment:
      - PORT=4000
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=perkbox
      - DATABASE_PASSWORD=perkbox
      - DATABASE_DATABASE=coupons
    ports:
      - "4000:4000"
    depends_on:
      - db
  migrate:
    build:
      context: .
      dockerfile: ./migration/Dockerfile
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=perkbox
      - DATABASE_PASSWORD=perkbox
      - DATABASE_DATABASE=coupons
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=perkbox
      - POSTGRES_DB=perkbox
      - POSTGRES_DB=coupons
  pgadmin:
    image: dpage/pgadmin4:4.11
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=thomas@sauvajon.eu
      - PGADMIN_DEFAULT_PASSWORD=perkbox
    ports:
      - "8080:80"
    depends_on:
      - db
